apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.fullname" . }}-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: {{ include "app.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.fullname" . }}-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: {{ include "app.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.fullname" . }}-metrics-binding
subjects:
- kind: ServiceAccount
  name: {{ include "app.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "app.fullname" . }}-metrics-reader
